[package]
name = "liblmdb-sys"
version = "0.2.2"
authors = ["Valerii Hiora <valerii.hiora@gmail.com>"]
links = "lmdb"
license = "MIT"
description = "LMDB native lib"
repository = "https://github.com/vhbit/lmdb-rs"
build = "build.rs"

[dependencies]
libc = "0.2"
[build-dependencies]
gcc = "0.3"
